apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-pmml-iris
    component: predictor
    serving.kserve.io/inferenceservice: spark-pmml-iris
  name: spark-pmml-iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-pmml-iris
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spark-pmml-iris
        component: predictor
        serving.kserve.io/inferenceservice: spark-pmml-iris
    spec:
      initContainers:
        - args:
            - gs://kfserving-examples/models/sparkpmml
            - /mnt/models
          image: kserve/storage-initializer:latest
          imagePullPolicy: IfNotPresent
          name: storage-initializer
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /mnt/models
              name: kserve-provision-location
      containers:
        - args:
            - --model_name=spark-pmml-iris
            - --model_dir=/mnt/models
            - --http_port=8080
          image: kserve/pmmlserver:latest
          imagePullPolicy: IfNotPresent
          name: kserve-container
          ports:
            - containerPort: 8080
              name: user-port
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      terminationGracePeriodSeconds: 300
      volumes:
      - emptyDir: {}
        name: kfserving-provision-location
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-pmml-iris
    component: predictor
    serving.kserve.io/inferenceservice: spark-pmml-iris
  name: spark-pmml-iris
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spark-pmml-iris
  type: ClusterIP
---

